ignoia/urls.py
from django.contrib import admin
from django.urls import path

from inscricao import views
from inscricao.views import CreateInscricao, comprovante

urlpatterns = [
    path('', views.index, name='index'),
    path('inscricao/', CreateInscricao.as_view(), name='inscricao'),
    path('obrigado/', comprovante, name='comprovante'),
]

inscricao/models.py
from django.db import models

from inscricao.validators import validate_CPF


class Curso(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Inscricao(models.Model):
    cpf = models.CharField(max_length=14, unique=True, verbose_name='CPF', validators=[validate_CPF])
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField(blank=True, null=True, verbose_name='Data de nascimento')
    telefone = models.CharField(max_length=25, help_text='Exemplo: (XX) XXXXX-XXXX')
    curso = models.ForeignKey(Curso, verbose_name='Curso de graduação', blank=True, null=True,
                              on_delete=models.DO_NOTHING, help_text='Selecione um curso da lista')
    email = models.EmailField(verbose_name='E-mail',
                              help_text='Através deste endereço eletrônico você receberá sua confirmação de inscrição')

inscricao/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field, HTML
from django import forms

from inscricao.models import Inscricao


class InscricaoForm(forms.ModelForm):
    curso_outro = forms.CharField(max_length=50, required=False, label='Outro',
                                  help_text='Informe o nome do seu curso')

    class Meta:
        model = Inscricao
        fields = '__all__'

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.layout = Layout(
            Div(
                Div(
                    Field('cpf'),
                    css_class='col'
                ),
                css_class='row'

            ),
            Div(
                Div(
                    Field('nome'),
                    css_class='col'
                ),
                css_class='row'

            ),
            Div(
                Div(
                    Field('email'),
                    css_class='col'
                ),
                css_class='row'

            ),
            Div(
                Div(
                    Field('data_nascimento'),
                    css_class='col'
                ),
                css_class='row'

            ),
            Div(
                Div(
                    Field('telefone'),
                    css_class='col'
                ),
                css_class='row'

            ),
            Div(
                HTML(
                    '<strong>Atenção!</strong><br/>'
                    'Você deverá apenas informar um dos campos abaixo. Selecione um item da lista ou caso não encontrar o seu curso informe o nome de outro curso de graduação.'
                ),
                css_class='alert alert-info'

            ),
            Div(
                Div(
                    Field('curso'),
                    css_class='col'
                ),
                Div(
                    Field('curso_outro'),
                    css_class='col'
                ),
                css_class='row'

            ),
        )
        return helper

inscricao/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView

from inscricao.forms import InscricaoForm
from inscricao.models import Inscricao, Curso


def index(request):
    context = {'page_title': 'Minha página'}
    return render(request, template_name='index.html', context=context)


class CreateInscricao(CreateView):
    form_class = InscricaoForm
    template_name = 'form.html'
    success_url = reverse_lazy('comprovante')

    def form_valid(self, form):
        curso_outro = form.cleaned_data['curso_outro']
        self.object = form.save()
        if form.cleaned_data['curso'] is None:
            if curso_outro:
                curso, created = Curso.objects.get_or_create(nome=curso_outro)
                self.object.curso = curso
                self.object.save()

        send_mail(
            'Inscrição realizada com sucesso',
            render_to_string('email.html', context={'inscricao': self.object}),
            settings.EMAIL_HOST_USER,
            [self.object.email],
            fail_silently=False,
        )
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Formulário de inscrição'
        return context


def comprovante(request):
    context = {'page_title': 'Minha página', 'success': True}
    return render(request, template_name='index.html', context=context)

templates/comprovante.html
{% extends 'template.html' %}

{% block content %}

    <div class="py-4 text-center" style="justify-items: center;">
        <h2>{{ page_title }}</h2>
        <p class="lead">Sua inscrição foi realizada com sucesso!</p>
    </div>

{% endblock %}

templates/email.html
Parabéns {{ inscricao.nome }}!

Seu código de inscrição é: #{{ inscricao.pk }}
Confira abaixo seus dados:

    CPF: {{ inscricao.cpf }}
    Nome: {{ inscricao.nome }}
    E-mail: {{ inscricao.email }}
    Data de nascimento: {{ inscricao.data_nascimento|default_if_none:'não informado' }}
    Telefone: {{ inscricao.telefone }}
    Curso: {{ inscricao.curso }}

Obrigado por insvrever-se.

templates/form.html
{% extends 'template.html' %}

{% load static crispy_forms_tags %}

{% block content %}

    <div class="py-4">
        <h2>{{ page_title }}</h2>
        <form method="post" class="my-4 pb-4">
            {% crispy form %}
            <button type="button" onclick="validate()" class="btn btn-primary">Inscrever-se</button>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $('#id_telefone').inputmask('(99) 9999[9]-9999');
        $('#id_cpf').inputmask('999.999.999-99');

        $('.dateinput').datepicker({
            format: 'dd/mm/yyyy',
            language: 'pt-BR',
        });

        $('input').attr('autocomplete', 'off');

        function validate() {
            let curso = $('#id_curso').val();
            let outro = $('#id_curso_outro').val();
            if (curso.trim().length == 0 && outro.trim().length == 0) {
                swal("Formulário incompleto", "Você precisa informar seu curso de graduação", "error");
            } else {
                $('form').submit();
            }
        }

        $('#id_curso').change(function () {
            $('#id_curso_outro').val(null);
        });
        $('#id_curso_outro').change(function () {
            $('#id_curso').val(null);
        });
    </script>
{% endblock %}

templates/index.html
{% extends 'template.html' %}

{% block content %}

    <div class="py-5 text-center">
        <h2>{{ page_title }}</h2>
        <p class="lead">
            Texto de descrição do que é isso
        </p>
        <a href="{% url 'inscricao' %}" class="btn btn-primary">Inscrever-se</a>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        {% if success %}
            $(function () {
                swal("Obrigado", "Sua inscrição foi realizada com sucesso!", "success");
            });
        {% endif %}
    </script>
{% endblock %}

templates/template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}{{ page_title }}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.css" />
    <style>
        html, body {
            height: 100%;
        }
    </style>
    {% block styles %}
    {% endblock %}
</head>
<body>


<div class="container">
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
{% block scripts %}
{% endblock %}
</body>
</html>